list_coins = [
    ['ETHBTC', 'BTCUSD', 'ETHUSD'],
    ['EOSBTC', 'BTCUSD', 'EOSUSD'],
    ['LTCBTC', 'BTCUSD', 'LTCUSD'],
    ['XRPBTC', 'BTCUSD', 'XRPUSD'],
    ['NEOBTC', 'BTCUSD', 'NEOUSD'],
    ['MKRBTC', 'BTCUSD', 'MKRUSD'],
    ['XMRBTC', 'BTCUSD', 'XMRUSD'],
    ['ZECBTC', 'BTCUSD', 'ZECUSD'],
    ['BABBTC', 'BTCUSD', 'BABUSD'],
    # ['RIFBTC', 'BTCUSD', 'RIFUSD'],
    # ['DASHBTC', 'BTCUSD', 'DASHUSD'],
    # ['IOTABTC', 'BTCUSD', 'IOTAUSD'],
    # ['BSVBTC', 'BTCUSD', 'BSVUSD'],
    # ['TRXBTC', 'BTCUSD', 'TRXUSD'],
    # ['XLMBTC', 'BTCUSD', 'XLMUSD'],
    # ['SNTBTC', 'BTCUSD', 'SNTUSD'],
    # ['ETPBTC', 'BTCUSD', 'ETPUSD'],
    # ['VETBTC', 'BTCUSD', 'VETUSD'],
    # ['OMGBTC', 'BTCUSD', 'OMGUSD'],
    # ['BTGBTC', 'BTCUSD', 'BTGUSD'],
    # ['VSYSBTC', 'BTCUSD', 'VSYSUSD'],
    # ['XTZBTC', 'BTCUSD', 'XTZUSD'],
    # ['DADIBTC', 'BTCUSD', 'DADIUSD'],
    # ['LYMBTC', 'BTCUSD', 'LYMUSD']
    ['MKRETH', 'ETHBTC', 'MKRBTC'],
    ['EOSETH', 'ETHBTC', 'EOSBTC'],
    ['ZRXETH', 'ETHBTC', 'ZRXBTC'],
    ['IOTAETH', 'ETHBTC', 'IOTABTC'],
    ['NEOETH', 'ETHBTC', 'NEOBTC'],
    ['VETETH', 'ETHBTC', 'VEOBTC'],
    ['SNTETH', 'ETHBTC', 'SNTBTC']
]